[versions]
agp = "8.6.0"
kotlin = "2.0.21"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2024.04.01"

retrofitVersion = "2.11.0"
refrofitLogingInterceptor = "4.10.0"
retrofitGson = "2.9.0"
kotlinSerializationJSON = "1.6.0"
navigationVersion = "2.8.7"
hilt = "2.51.1"
ksp = "2.0.21-1.0.27"
room = "2.6.1"
hilt-navigation-compose = "1.2.0"
datastoreCoreAndroid = "1.1.3"
glideVersion = "1.0.0-beta01"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Retrofit
# https://square.github.io/retrofit/
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofit-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "refrofitLogingInterceptor" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitGson" }

# Serialization
# https://kotlinlang.org/docs/serialization.html#formats
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerializationJSON" }

#Datastore
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreCoreAndroid" }

# Navigation
# https://developer.android.com/develop/ui/compose/navigation
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationVersion" }
navigation-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

# Hilt android
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

#Room DB
# https://developer.android.com/training/data-storage/room
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = {group = "androidx.room", name="room-ktx", version.ref="room"}

#Glide
glide = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideVersion" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Hilt
# https://developer.android.com/training/dependency-injection/hilt-android
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# KSP
# https://developer.android.com/build/migrate-to-ksp
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationJSON" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

